/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import controller.ExpencesCategory;
import controller.ExpensesCategoryController;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.UiSettings;

/**
 *
 * @author Chalindu
 */
public class ExpensesCategoryPanel extends javax.swing.JPanel {

    /**
     * @return the categoryId
     */
    public int getCategoryId() {
        return categoryId;
    }

    /**
     * @param categoryId the categoryId to set
     */
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
        if(categoryId>0){
            btnSave.setText("Update");
        }else{
            btnSave.setText("Add");
        }
    }

    MainView mainView;
    private int categoryId;
    ExpencesCategory expencesCategory;
    ManageExpencesPanel manageExpencesPanel;
    
    /**
     * Creates new form ExpensesCategoryPanel
     * @param mainView
     * @param manageExpencesPanel
     */
    public ExpensesCategoryPanel(MainView mainView,ManageExpencesPanel manageExpencesPanel) {
        initComponents();
        this.mainView=mainView;
        this.manageExpencesPanel=manageExpencesPanel;
        UiSettings.tableProperties(tblcategory);
        loadTable("");
    }
    
    public void loadTable(String search){
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        DefaultTableModel dtm=(DefaultTableModel)tblcategory.getModel();
        dtm.setRowCount(0);
        String sql="SELECT * FROM `expences_category`";
        if(search.length()>0){
            sql+=" WHERE `category` LIKE '%"+search+"%';";
        }
        ExpencesCategory ec=new ExpencesCategory();
        ResultSet rs=ec.read(sql);
        try {
            while(rs.next()){
                ec=new ExpencesCategory();
                ec.setId(rs.getInt("id"));
                ec.setCategory(rs.getString("category"));
                ArrayList al=new ArrayList();
                al.add(ec);
                dtm.addRow(al.toArray());
            }
        } catch (SQLException ex) {
            Logger.getLogger(ExpensesCategoryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void save(){
        if(mainView.isEmptyField(txtCategory, "Please enter the category")){
            return;
        }
        if(getCategoryId()>0){
            ExpencesCategory ec=new ExpencesCategory();
            ec.setId(getCategoryId());
            ec.setCategory(txtCategory.getText());
            ExpensesCategoryController ecc=new ExpensesCategoryController();
            boolean b=ecc.update(ec);
            if(b){
                txtSearch.setText("");
                loadTable("");
                txtCategory.setText("");
            }
        }else{
            ExpencesCategory ec=new ExpencesCategory();
            ec.setCategory(txtCategory.getText());
            ExpensesCategoryController ecc=new ExpensesCategoryController();
            boolean b=ecc.create(ec);
            if(b){
                txtSearch.setText("");
                loadTable("");
                txtCategory.setText("");
            }
        }
        manageExpencesPanel.loadCategory();
        setCategoryId(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcategory = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Expenses category");

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        tblcategory.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tblcategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblcategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblcategoryMouseClicked(evt);
            }
        });
        tblcategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblcategoryKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblcategory);
        if (tblcategory.getColumnModel().getColumnCount() > 0) {
            tblcategory.getColumnModel().getColumn(0).setResizable(false);
        }

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/close.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/pencil.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/drop.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Expense category");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 44;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 10);
        jPanel1.add(jLabel2, gridBagConstraints);

        txtCategory.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCategoryKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 226;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 10);
        jPanel1.add(txtCategory, gridBagConstraints);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/save.png"))); // NOI18N
        btnSave.setText("Add");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 163, 11, 10);
        jPanel1.add(btnSave, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSearch)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnClose))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEdit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDelete))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 208, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        mainView.removeTab(this);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        loadTable(txtSearch.getText());
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tblcategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblcategoryMouseClicked
        if(tblcategory.getRowCount()>0 && tblcategory.getSelectedRow()>-1){
            btnEdit.setEnabled(true);
            btnDelete.setEnabled(true);
            expencesCategory=(ExpencesCategory)tblcategory.getValueAt(tblcategory.getSelectedRow(),0);
        }
    }//GEN-LAST:event_tblcategoryMouseClicked

    private void tblcategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblcategoryKeyReleased
        if(tblcategory.getRowCount()>0 && tblcategory.getSelectedRow()>-1){
            btnEdit.setEnabled(true);
            btnDelete.setEnabled(true);
            expencesCategory=(ExpencesCategory)tblcategory.getValueAt(tblcategory.getSelectedRow(),0);
        }
    }//GEN-LAST:event_tblcategoryKeyReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        ExpencesCategory ec=new ExpencesCategory();
        if(ec.checkCategory(expencesCategory.getId())){
            JOptionPane.showMessageDialog(this, "You can't delete this category. because this category is used.");
        }else{
            int i=JOptionPane.showConfirmDialog(this, "do you want to delete this category?");
            if(i==0){
                ExpensesCategoryController ecc=new ExpensesCategoryController();
                ecc.delete(expencesCategory);
                loadTable("");
                manageExpencesPanel.loadCategory();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        ExpencesCategory ec=new ExpencesCategory();
        if(ec.checkCategory(expencesCategory.getId())){
            JOptionPane.showMessageDialog(this, "You can't edit this category. because this category is used.");
        }else{
            setCategoryId(expencesCategory.getId());
            txtCategory.setText(expencesCategory.getCategory());
        }
        
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        save();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoryKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            save();
        }
    }//GEN-LAST:event_txtCategoryKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblcategory;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
