/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import controller.InventoryCategory;
import controller.InventoryCategoryController;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.UiSettings;

/**
 *
 * @author Chalindu
 */
public class ItemCategoryPanel extends javax.swing.JPanel {

    /**
     * @return the categoryId
     */
    public int getCategoryId() {
        return categoryId;
    }

    /**
     * @param categoryId the categoryId to set
     */
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
        if (categoryId > 0) {
            btnSave.setText("Update");
        } else {
            btnSave.setText("Add");
        }
    }

    MainView mainView;
    ManageInventoryPanel manageInventoryPanel;
    InventoryCategory inventoryCategory;
    private int categoryId;

    /**
     * Creates new form ItemCategoryPanel
     *
     * @param mainView
     * @param manageInventoryPanel
     */
    public ItemCategoryPanel(MainView mainView, ManageInventoryPanel manageInventoryPanel) {
        initComponents();
        this.mainView = mainView;
        this.manageInventoryPanel = manageInventoryPanel;
        UiSettings.tableProperties(tblItemCategory);
        loadTable("");
    }

    public void loadTable(String search) {
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        DefaultTableModel dtm = (DefaultTableModel) tblItemCategory.getModel();
        dtm.setRowCount(0);
        String sql = "SELECT * FROM `inventory_category`";
        if (search.length() > 0) {
            sql += " WHERE `category` LIKE '%" + search + "%';";
        } else {
            sql += ";";
        }
        InventoryCategory ic = new InventoryCategory();
        ResultSet rs = ic.read(sql);
        try {
            while (rs.next()) {
                ic = new InventoryCategory();
                ic.setId(rs.getInt("id"));
                ic.setCategory(rs.getString("category"));
                ArrayList<Object> al = new ArrayList();
                al.add(ic);
                dtm.addRow(al.toArray());
            }
        } catch (SQLException ex) {
            Logger.getLogger(ItemCategoryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void save(){
        if(mainView.isEmptyField(txtCategory, "please enter the category")){
            return;
        }
        if(getCategoryId()>0){
            System.out.println("edit");
            InventoryCategory ic=new InventoryCategory();
            ic.setId(getCategoryId());
            ic.setCategory(txtCategory.getText());
            InventoryCategoryController icc=new InventoryCategoryController();
            boolean b=icc.update(ic);
            if(b){
                loadTable("");
                txtSearch.setText("");
                txtCategory.setText("");
            }
        }else{
            System.out.println("add");
            InventoryCategory ic=new InventoryCategory();
            ic.setCategory(txtCategory.getText());
            InventoryCategoryController icc=new InventoryCategoryController();
            boolean b=icc.create(ic);
            if(b){
                loadTable("");
                txtSearch.setText("");
                txtCategory.setText("");
            }
        }
        manageInventoryPanel.loadCategory();
        setCategoryId(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemCategory = new javax.swing.JTable();
        btnClose = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        jButton3.setText("jButton3");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Item category panel");

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        tblItemCategory.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tblItemCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItemCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemCategoryMouseClicked(evt);
            }
        });
        tblItemCategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblItemCategoryKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblItemCategory);
        if (tblItemCategory.getColumnModel().getColumnCount() > 0) {
            tblItemCategory.getColumnModel().getColumn(0).setResizable(false);
        }

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/close.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/pencil.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.setEnabled(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/drop.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Item category");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 10);
        jPanel1.add(jLabel2, gridBagConstraints);

        txtCategory.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCategoryKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 257;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 10);
        jPanel1.add(txtCategory, gridBagConstraints);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/save.png"))); // NOI18N
        btnSave.setText("Add");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 194, 11, 10);
        jPanel1.add(btnSave, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(432, 432, 432)
                                .addComponent(btnClose)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEdit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDelete)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        mainView.removeTab(this);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        loadTable(txtSearch.getText());
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        setCategoryId(inventoryCategory.getId());
        txtCategory.setText(inventoryCategory.getCategory());
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblItemCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemCategoryMouseClicked
        if (tblItemCategory.getRowCount() > 0 && tblItemCategory.getSelectedRow() > -1) {
            btnEdit.setEnabled(true);
            btnDelete.setEnabled(true);
            inventoryCategory = (InventoryCategory) tblItemCategory.getValueAt(tblItemCategory.getSelectedRow(), 0);
        }

    }//GEN-LAST:event_tblItemCategoryMouseClicked

    private void tblItemCategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblItemCategoryKeyReleased
        if (tblItemCategory.getRowCount() > 0 && tblItemCategory.getSelectedRow() > -1) {
            btnEdit.setEnabled(true);
            btnDelete.setEnabled(true);
            inventoryCategory = (InventoryCategory) tblItemCategory.getValueAt(tblItemCategory.getSelectedRow(), 0);
        }
    }//GEN-LAST:event_tblItemCategoryKeyReleased

    private void txtCategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoryKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            save();
        }
    }//GEN-LAST:event_txtCategoryKeyReleased

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        save();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        boolean b=inventoryCategory.checkCategoryUsed(inventoryCategory.getId());
        if(b){
            JOptionPane.showMessageDialog(this, "You can't delete this category. because this category is used.");
        }else{
            int i=JOptionPane.showConfirmDialog(this, "do you want to delete this category");
            if(i==0){
                InventoryCategoryController icc=new InventoryCategoryController();
                icc.delete(inventoryCategory);
                loadTable("");
                manageInventoryPanel.loadCategory();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItemCategory;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
