/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import controller.Employee;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Chalindu
 */
public final class UpdateDefaultEmployeePanel extends javax.swing.JPanel {

    /**
     * @return the employee1_id
     */
    public int getEmployee1_id() {
        return employee1_id;
    }

    /**
     * @param employee1_id the employee1_id to set
     */
    public void setEmployee1_id(int employee1_id) {
        this.employee1_id = employee1_id;
        Employee e = new Employee();
        ResultSet rs = e.read("SELECT `name` FROM `employee` WHERE `id`='" + employee1_id + "';");
        try {
            if (rs.last()) {
                txtEmp1.setText(rs.getString("name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageWoodLoadPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @return the employee2_id
     */
    public int getEmployee2_id() {
        return employee2_id;
    }

    /**
     * @param employee2_id the employee2_id to set
     */
    public void setEmployee2_id(int employee2_id) {
        this.employee2_id = employee2_id;
        Employee e = new Employee();
        ResultSet rs = e.read("SELECT `name` FROM `employee` WHERE `id`='" + employee2_id + "';");
        try {
            if (rs.last()) {
                txtEmp2.setText(rs.getString("name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageWoodLoadPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public boolean UpdateDefaultEmployees(){
        Employee e=new Employee();
        String sql="UPDATE `default_employee` SET `emp_1_id`='"+String.valueOf(getEmployee1_id())+"',`emp_2_id`='"+String.valueOf(getEmployee2_id())+"';";
        boolean b=e.update(sql);
        return b;
    }
    
    public void setEmployees(){
        Employee e=new Employee();
        String sql="SELECT * FROM `default_employee`";
        ResultSet rs=e.read(sql);
        try {
            if(rs.last()){
                setEmployee1_id(rs.getInt("emp_1_id"));
                setEmployee2_id(rs.getInt("emp_2_id"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateDefaultEmployeePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    MainView mainView;
    ManageWoodLoadPanel mwlp;
    private int employee1_id;
    private int employee2_id;
    
    /**
     * Creates new form UpdateDefaultEmployeePanel
     * @param mainView
     * @param mwlp
     */
    public UpdateDefaultEmployeePanel(MainView mainView,ManageWoodLoadPanel mwlp) {
        initComponents();
        this.mainView=mainView;
        this.mwlp=mwlp;
        setEmployees();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmp1 = new javax.swing.JTextField();
        txtEmp2 = new javax.swing.JTextField();
        btnSelectEmp1 = new javax.swing.JButton();
        btnSelectEmp2 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton4.setText("jButton4");

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/close.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Default employee panel");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Employee 1 :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Employee 2 :");

        txtEmp1.setEditable(false);
        txtEmp1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtEmp2.setEditable(false);
        txtEmp2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        btnSelectEmp1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSelectEmp1.setText("...");
        btnSelectEmp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectEmp1ActionPerformed(evt);
            }
        });

        btnSelectEmp2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSelectEmp2.setText("...");
        btnSelectEmp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectEmp2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmp1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmp2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelectEmp1)
                    .addComponent(btnSelectEmp2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectEmp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectEmp2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/save.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose)))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnUpdate))
                .addContainerGap(257, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectEmp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectEmp1ActionPerformed
        EmployeePanel ep=new EmployeePanel(mainView, this, 1);
        mainView.addTab("Select first employee", ep);
    }//GEN-LAST:event_btnSelectEmp1ActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        mainView.removeTab(this);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSelectEmp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectEmp2ActionPerformed
        EmployeePanel ep=new EmployeePanel(mainView, this, 2);
        mainView.addTab("Select first employee", ep);
    }//GEN-LAST:event_btnSelectEmp2ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if(!(getEmployee1_id()>0)){
            JOptionPane.showMessageDialog(this, "Please select the first employee");
            return;
        }
        if(!(getEmployee2_id()>0)){
            JOptionPane.showMessageDialog(this, "Please select the Second employee");
            return;
        }
        boolean b=UpdateDefaultEmployees();
        if(b){
            mwlp.setDefaultEmployee();
            mainView.selectComponent(mwlp);
            mainView.removeTab(this);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSelectEmp1;
    private javax.swing.JButton btnSelectEmp2;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtEmp1;
    private javax.swing.JTextField txtEmp2;
    // End of variables declaration//GEN-END:variables
}
