/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viewer;

import controller.WoodCategory;
import controller.WoodCategoryController;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.UiSettings;

/**
 *
 * @author Chalindu
 */
public final class WoodCategoryPanel extends javax.swing.JPanel {

    /**
     * @return the categoryId
     */
    public int getCategoryId() {
        return categoryId;
    }

    /**
     * @param categoryId the categoryId to set
     */
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
        if(categoryId>0){
            btnSave.setText("Update");
        }else{
            btnSave.setText("Add");
        }
    }

    MainView mainView;
    WoodLoadInputPanel woodLoadInputPanel;
    private int categoryId;
    WoodCategory woodCategory;

    /**
     * Creates new form WoodCategoryPanel
     *
     * @param mainView
     * @param woodLoadInputPanel
     */
    public WoodCategoryPanel(MainView mainView, WoodLoadInputPanel woodLoadInputPanel) {
        initComponents();
        this.mainView = mainView;
        this.woodLoadInputPanel = woodLoadInputPanel;
        UiSettings.tableProperties(tblWoodCategory);
        loadTable();
    }

    public void loadTable() {
        btnEdit.setEnabled(false);
        btnDelete.setEnabled(false);
        String s = txtSearch.getText();
        DefaultTableModel dtm = (DefaultTableModel) tblWoodCategory.getModel();
        dtm.setRowCount(0);
        String sql = "SELECT * FROM `wood_category`";
        if (s.length() > 0) {
            sql += " WHERE `category` LIKE '%" + s + "%';";
        }
        WoodCategory wc = new WoodCategory();
        ResultSet rs = wc.read(sql);
        try {
            while (rs.next()) {
                wc = new WoodCategory();
                wc.setId(rs.getInt("id"));
                wc.setCategory(rs.getString("category"));
                ArrayList<Object> al = new ArrayList();
                al.add(wc);
                dtm.addRow(al.toArray());
            }
        } catch (SQLException ex) {
            Logger.getLogger(WoodCategoryPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void save() {
        if (mainView.isEmptyField(txtCategory, "Please enter the category.")) {
            return;
        }
        if (getCategoryId() > 0) {
            woodCategory = new WoodCategory();
            woodCategory.setId(getCategoryId());
            woodCategory.setCategory(txtCategory.getText());
            WoodCategoryController wcc = new WoodCategoryController();
            boolean b=wcc.update(woodCategory);
            if(b){
                loadTable();
                txtSearch.setText("");
                txtCategory.setText("");
            }
        } else {
            woodCategory=new WoodCategory();
            woodCategory.setCategory(txtCategory.getText());
            WoodCategoryController wcc = new WoodCategoryController();
            boolean b=wcc.create(woodCategory);
            if(b){
                loadTable();
                txtSearch.setText("");
                txtCategory.setText("");
            }
        }
        woodLoadInputPanel.loadCategory();
        setCategoryId(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWoodCategory = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        jButton4.setText("jButton4");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Wood category panel");

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        tblWoodCategory.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tblWoodCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Wood category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblWoodCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblWoodCategoryMouseClicked(evt);
            }
        });
        tblWoodCategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblWoodCategoryKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblWoodCategory);
        if (tblWoodCategory.getColumnModel().getColumnCount() > 0) {
            tblWoodCategory.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Wood category");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 239);
        jPanel1.add(jLabel2, gridBagConstraints);

        txtCategory.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCategory.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCategoryKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 155;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 0, 239);
        jPanel1.add(txtCategory, gridBagConstraints);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/save.png"))); // NOI18N
        btnSave.setText("Add");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 92, 53, 239);
        jPanel1.add(btnSave, gridBagConstraints);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/pencil.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/drop.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/close.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(btnClose)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        loadTable();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tblWoodCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWoodCategoryMouseClicked
        if (tblWoodCategory.getRowCount() > 0 && tblWoodCategory.getSelectedRow() > -1) {
            btnEdit.setEnabled(true);
            btnDelete.setEnabled(true);
            woodCategory = (WoodCategory) tblWoodCategory.getValueAt(tblWoodCategory.getSelectedRow(), 0);

        }
    }//GEN-LAST:event_tblWoodCategoryMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        setCategoryId(woodCategory.getId());
        txtCategory.setText(woodCategory.getCategory());
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtCategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCategoryKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            save();                            }
    }//GEN-LAST:event_txtCategoryKeyReleased

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        save();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        mainView.removeTab(this);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        boolean b=woodCategory.checkCategory(getCategoryId());
        if(b){
            JOptionPane.showMessageDialog(this, "you can't delete this category. becuase this category has records in the system.");
        }else{
            int i=JOptionPane.showConfirmDialog(this, "Are you want to delete this category");
            if(i==0){
                WoodCategoryController wcc=new WoodCategoryController();
                wcc.delete(woodCategory);
                loadTable();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblWoodCategoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblWoodCategoryKeyReleased
        if (tblWoodCategory.getRowCount() > 0 && tblWoodCategory.getSelectedRow() > -1) {
            btnEdit.setEnabled(true);
            btnDelete.setEnabled(true);
            woodCategory = (WoodCategory) tblWoodCategory.getValueAt(tblWoodCategory.getSelectedRow(), 0);
        }
    }//GEN-LAST:event_tblWoodCategoryKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblWoodCategory;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
